env:
    credentials: "ENCRYPTED[!fcd2a3e34b812731f10709c885aff512d0d6bb5cc3b1297b18e65c615b9656f853488dbfd96f98deede5f57700c0a6c0!]"

task:
  name: "Build Qassa AOSP ROM"
  timeout_in: 480m
  container:
    image: inok2341/anu:latest
    cpu: 8
    memory: 32G

  build_script:
    - export DEBIAN_FRONTEND=noninteractive
    - export BUILD_USERNAME="minusiq"
    - export BUILD_HOSTNAME="Din"
    - export KBUILD_BUILD_USER="minusiq"
    - export KBUILD_BUILD_HOST="din"

    # Setup Git and credentials
    - git config --global user.name "minusiq"
    - git config --global user.email "endangsoekamti021@gmail.com"
    - echo "$credentials" > ~/.git-credentials
    - git config --global credential.helper store --file=~/.git-credentials

    # Setup Rclone for cloud storage
    - mkdir -p ~/.config/rclone
    - echo "$rcloneconfig" > ~/.rclone.conf

    # Download and setup repo tool
    - mkdir -p ~/bin
    - curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
    - chmod a+x ~/bin/repo

    # Initialize the Qassa manifest and sync
    - mkdir -p ~/rom
    - cd ~/rom
    - repo init -q --no-repo-verify --depth=1 -u https://github.com/keepQASSA/manifest.git -b Q -g default,-mips,-darwin,-notdefault
    - git clone --depth 1 https://github.com/minusiq/local_manifest.git -b main .repo/local_manifests
    - rm -rf .repo/repo && git clone https://gerrit.googlesource.com/git-repo .repo/repo
    - sed -i 's|ssh://git@github.com|https://github.com|g' .repo/manifests/snippets/qassa.xml
    - repo sync -c -j8 --force-sync --no-clone-bundle --no-tags

    # Build Qassa ROM
    - source build/envsetup.sh
    - lunch qassa_RMX2020-user
    - make -j8

    # Upload artifacts (adjust paths as per your setup)
    - ./upload.sh
    - rclone copy ~/rom/out/target/product/RMX2020/*.zip qassa:qassa -P
    - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build $(ls ~/rom/out/target/product/RMX2020/qassa*.zip) completed!"

