env:
    credentials: "ENCRYPTED[!fcd2a3e34b812731f10709c885aff512d0d6bb5cc3b1297b18e65c615b9656f853488dbfd96f98deede5f57700c0a6c0!]"
    rcloneconfig: "ENCRYPTED[!90b21546e199df8309441e7b9dd5e9ea6b64cbc05c54eff3b11752309eab5efbaa402f0585603e329dce6a211fb23a5b!]"
    tokentl: "ENCRYPTED[!3f819de0dc823a203b591064c875bd11e6a3c071987ccdf0642fde534fcf0a10fd74501b08371d15b6461fa24a1c4dc0!]"
    idtl: "ENCRYPTED[!245751fe5b95fc14c1f371af6e07a5a8fd6499c32197c73e23609c32f149f202f78a4feaa990d504e66363a3baaf0d96!]"
    lunch: lunch qassa_RMX2020-user
    make: make qassa

task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 480m
  container:
      image: inok2341/anu:latest
      cpu: 8
      memory: 32G

  Build-Env-Setup_background_script:
       - export DEBIAN_FRONTEND=noninteractive
       - mkdir -p ~/.config/rclone
       - echo "$rcloneconfig" > ~/.rclone.conf
       - git config --global user.name "minusiq"
       - git config --global user.email "endangsoekamti021@gmail.com"
       - echo "$credentials" > ~/.git-credentials
       - git config --global credential.helper store --file=~/.git-credentials
       - mkdir -p ~/ccache
       - rclone copy qassa:qassa/ccache.tar.gz ~/ -P
       - cd ~/
       - time tar xf ccache.tar.gz
       - cd ~/

  Storage-Checker_background_script:
      - df -h
      - lsblk
      - ls -l -a -h
      - ./w.sh

  Sync_script:
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Start sync qassa Source"
      - mkdir -p ~/rom
      - cd ~/rom
      - sudo curl --create-dirs -L -o /usr/local/bin/repoo -O -L https://storage.googleapis.com/git-repo-downloads/repo
      - sudo chmod a+rx /usr/local/bin/repoo
      - repo init -q --no-repo-verify --depth=1 -u https://github.com/keepQASSA/manifest.git -b Q -g default,-mips,-darwin,-notdefault
      - git clone --depth 1 https://github.com/minusiq/local_manifest.git -b main .repo/local_manifests
      - rm -rf .repo/repo && git clone https://gerrit.googlesource.com/git-repo .repo/repo
      - sed -i 's|ssh://git@github.com|https://github.com|g' .repo/manifests/snippets/qassa.xml
#      - repoo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8 --fail-fast
      - repo sync -c -j8 --force-sync --no-clone-bundle --no-tags
      - sed -i 's| -u||g' vendor/qassa/config/branding.mk
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Sync Completed!"

  Build_script:
      - export BUILD_USERNAME="minusiq"
      - export BUILD_HOSTNAME="Din"
      - export KBUILD_BUILD_USER="minusiq"
      - export KBUILD_BUILD_HOST="din"
#      - export WITH_GAPPS=true
      - sudo ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build qassa for RMX2020 Started!"
      - ./collect.sh
#      - ./final.sh
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build $(cd ~/rom/out/target/product/RMX2020/ && ls qassa*.zip) Completed!"

  Upload_script:
      - ./upload.sh
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Compres ccache"
      - ./ziping.sh
      - cd ~/
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Uploading ccache...."
      - rclone copy ccache.tar.gz qassa:qassa -P
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Ccache Uploaded Successfully!"
